<a href="https://colab.research.google.com/github/eghrthrjdtsed/-------------------------/blob/master/Home_work_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [592]:
import re

In [593]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [594]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [595]:
len(text)

205

In [596]:
num_characters = 34 #33 буквы + пробел

In [597]:
import keras
from keras.preprocessing.text import Tokenizer

In [598]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [599]:
tokenizer.fit_on_texts(text)

In [600]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [601]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [602]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [603]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [604]:
import numpy as np

In [605]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [606]:
len(X)

199

In [607]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [608]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [609]:
from keras.layers import *
from keras.models import Sequential

In [610]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_34 (SimpleRNN)   (None, 500)               267500    
                                                                 
 dense_34 (Dense)            (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [611]:
from keras.layers import SimpleRNN


In [612]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 2s 29ms/step - loss: 3.4217 - accuracy: 0.0503
Epoch 2/100
7/7 [==============================] - 0s 17ms/step - loss: 2.4162 - accuracy: 0.2864
Epoch 3/100
7/7 [==============================] - 0s 19ms/step - loss: 1.8751 - accuracy: 0.4874
Epoch 4/100
7/7 [==============================] - 0s 18ms/step - loss: 1.5213 - accuracy: 0.5276
Epoch 5/100
7/7 [==============================] - 0s 17ms/step - loss: 1.1994 - accuracy: 0.6432
Epoch 6/100
7/7 [==============================] - 0s 16ms/step - loss: 1.0440 - accuracy: 0.6884
Epoch 7/100
7/7 [==============================] - 0s 18ms/step - loss: 0.8972 - accuracy: 0.7387
Epoch 8/100
7/7 [==============================] - 0s 17ms/step - loss: 0.8129 - accuracy: 0.7739
Epoch 9/100
7/7 [==============================] - 0s 17ms/step - loss: 0.7296 - accuracy: 0.7789
Epoch 10/100
7/7 [==============================] - 0s 18ms/step - loss: 0.6101 - accuracy: 0.8492
Epoch 11/100
7/7 [=

In [613]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [614]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 23ms/step
утренновтовн  и верьте в свою способность достигать отли


## Слова

In [630]:
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

In [644]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '')

In [662]:
texts

'Вы — лучший ответ на проблемы, которые возникли в понедельник.\nДумайте позитивно и верьте в свою способность достигать отличных результатов.\nЕсли вы смогли в понедельник подняться с постели, значит вы супер герой.'

In [646]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–" —#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)

tokenizer.fit_on_texts([texts])

In [647]:
sequences = tokenizer.texts_to_sequences([texts])[0]
vocab_size = len(tokenizer.word_index) + 1

In [663]:
sequences

[1,
 4,
 5,
 6,
 7,
 8,
 9,
 2,
 3,
 10,
 11,
 12,
 13,
 2,
 14,
 15,
 16,
 17,
 18,
 19,
 1,
 20,
 2,
 3,
 21,
 22,
 23,
 24,
 1,
 25,
 26]

In [664]:
vocab_size

27

In [648]:
inp_words = 3
X = []
Y = []
for i in range(len(sequences) - inp_words):
    X.append(sequences[i:i + inp_words])
    Y.append(sequences[i + inp_words])

X = np.array(X)
Y = np.array(Y)

In [660]:
X

array([[ 1,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9,  2],
       [ 9,  2,  3],
       [ 2,  3, 10],
       [ 3, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13,  2],
       [13,  2, 14],
       [ 2, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19,  1],
       [19,  1, 20],
       [ 1, 20,  2],
       [20,  2,  3],
       [ 2,  3, 21],
       [ 3, 21, 22],
       [21, 22, 23],
       [22, 23, 24],
       [23, 24,  1],
       [24,  1, 25]])

In [661]:
Y

array([ 6,  7,  8,  9,  2,  3, 10, 11, 12, 13,  2, 14, 15, 16, 17, 18, 19,
        1, 20,  2,  3, 21, 22, 23, 24,  1, 25, 26])

In [649]:
model = Sequential([
    Embedding(vocab_size, 50, input_length=inp_words),
    SimpleRNN(128),
    Dense(vocab_size, activation='softmax')
])

In [650]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [651]:
history = model.fit(X, Y, batch_size=32, epochs=20)

Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 3.3062 - accuracy: 0.0000e+00
Epoch 2/20
1/1 [==============================] - 0s 16ms/step - loss: 3.2777 - accuracy: 0.0357
Epoch 3/20
1/1 [==============================] - 0s 15ms/step - loss: 3.2493 - accuracy: 0.2857
Epoch 4/20
1/1 [==============================] - 0s 18ms/step - loss: 3.2206 - accuracy: 0.3571
Epoch 5/20
1/1 [==============================] - 0s 17ms/step - loss: 3.1915 - accuracy: 0.4286
Epoch 6/20
1/1 [==============================] - 0s 16ms/step - loss: 3.1618 - accuracy: 0.5357
Epoch 7/20
1/1 [==============================] - 0s 19ms/step - loss: 3.1312 - accuracy: 0.7500
Epoch 8/20
1/1 [==============================] - 0s 20ms/step - loss: 3.0994 - accuracy: 0.8571
Epoch 9/20
1/1 [==============================] - 0s 14ms/step - loss: 3.0664 - accuracy: 0.8929
Epoch 10/20
1/1 [==============================] - 0s 23ms/step - loss: 3.0317 - accuracy: 0.9286
Epoch 11/20
1/1 [==========

In [652]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences

In [657]:
def buildPhrase(text, model, tokenizer, max_len=20):
    result = text.lower()
    input_text = text
    for _ in range(max_len):
        sequence = tokenizer.texts_to_sequences([input_text])[0]
        sequence = pad_sequences([sequence], maxlen=inp_words, padding='pre')
        pred = model.predict(sequence)
        pred_index = np.argmax(pred)
        pred_word = tokenizer.index_word[pred_index]
        result += " " + pred_word
        input_text = input_text.split()[1:] + [pred_word]
        input_text = ' '.join(input_text)
    return result

In [659]:
initial_text = "позитив добавляет годы"
predicted_phrase = buildPhrase(initial_text, model, tokenizer)
print(predicted_phrase)

1/1 [==============================] - 0s 21ms/step
позитив добавляет годы в понедельник думайте позитивно и верьте в свою способность достигать отличных результатов если вы смогли в понедельник подняться с постели


В данном коде создана функция __buildPhrase__, которая используется для генерации последовательности слов на основе модели рекуррентной нейронной сети. Вот основные шаги, предпринятые в этой функции:

__Подготовка входных данных__: Исходный текст преобразуется в нижний регистр, чтобы обеспечить нормализацию данных. Далее текст токенизируется с использованием токенизатора, связанного с моделью.

**Генерация слов**: Затем выполняется цикл, в котором предсказывается следующее слово в последовательности. Для этого сначала преобразуется текущая последовательность слов в последовательность токенов, а затем выполняется предсказание с использованием модели.

__Обновление входных данных__: Полученное предсказанное слово добавляется к сгенерированной последовательности, а затем обновляется входной текст для следующей итерации путем удаления первого слова из последовательности и добавления предсказанного слова.

__Завершение цикла__: Этот процесс повторяется до тех пор, пока не будет сгенерирована требуемая длина последовательности или не будет достигнут критерий останова.

__Возврат результата__: В конце функции возвращается сгенерированная последовательность слов.

##Вывод:
В ходе работы была создана функция __buildPhrase__, которая использует предварительно обученную рекуррентную нейронную сеть для генерации последовательности слов на основе заданного входного текста. Эта функция позволяет прогнозировать следующее слово в последовательности и добавлять его к сгенерированному тексту, обновляя входные данные для последующих итераций. </br>

Основные шаги работы включали подготовку данных, генерацию слов с помощью модели, обновление входных данных и завершение цикла в соответствии с заданным критерием останова. </br>

Функция была реализована с использованием библиотеки __Keras__ и предполагает использование предварительно обученной модели рекуррентной нейронной сети, а также _токенизатора_, обученного на исходном тексте. Результатом работы функции является сгенерированная последовательность слов, которая может быть использована для создания текста на основе заданного контекста. </br>

Таким образом, функция __buildPhrase__ представляет собой полезный инструмент для автоматической генерации текста на основе предварительно обученной модели и может быть использована в различных приложениях, таких как автозаполнение текста, генерация заголовков или создание простых прогнозов.